# Note: conda dependencies have only 1 "="
#       pip dependencies have 2 "=="
# Fuse pip dependencies together under one " - pip" item
#       Otherwise, only some of the are installed, because conda creates a temporary requirements.txt file
#       only the last -pip section

name: PROJECT_NAME

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - jupyterlab

  - pip:
    # All pip dependencies